//! XYZ 格式文件写入器

use molflow_core::Molecule;
use std::fs::File;
use std::io::{Write, BufWriter};
use anyhow::{Result, Context};

/// 将分子写入 XYZ 格式文件
/// 
/// # 示例
/// ```no_run
/// use molflow_core::Molecule;
/// use molflow_io::write_xyz;
/// 
/// let molecule = Molecule::new();
/// write_xyz(&molecule, "output.xyz").unwrap();
/// ```
pub fn write_xyz(molecule: &Molecule, path: &str) -> Result<()> {
    let file = File::create(path)
        .context(format!("Failed to create file: {}", path))?;
    let mut writer = BufWriter::new(file);
    
    // 第一行: 原子数
    writeln!(writer, "{}", molecule.atom_count())?;
    
    // 第二行: 注释(分子名称或空白)
    let comment = molecule.name.as_deref().unwrap_or("Generated by ChemTools");
    writeln!(writer, "{}", comment)?;
    
    // 原子坐标
    for atom in &molecule.atoms {
        writeln!(
            writer,
            "{:<2}  {:>12.6}  {:>12.6}  {:>12.6}",
            atom.element,
            atom.position.x,
            atom.position.y,
            atom.position.z
        )?;
    }
    
    writer.flush()?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use molflow_core::Atom;
    use nalgebra::Vector3;
    
    #[test]
    fn test_xyz_writing() {
        let mut molecule = Molecule::new();
        molecule.add_atom(Atom::new("C", Vector3::new(0.0, 0.0, 0.0)));
        
        // 实际测试需要使用临时文件
    }
}
